require "test_helper"
require "tmpdir"

class DefinitionLoaderTest < DefinitionTestCase
  teardown do
    Object.send(:remove_const, :LoaderProbeCreated) if Object.const_defined?(:LoaderProbeCreated, false)
    Object.send(:remove_const, :LoaderProbeLifecycle) if Object.const_defined?(:LoaderProbeLifecycle, false)
  end

  test "load! returns the definitions declared under the path" do
    Dir.mktmpdir do |dir|
      File.write(File.join(dir, "loader_probe_created.rb"), <<~RUBY)
        class LoaderProbeCreated < EventEngine::EventDefinition
          event_name :loader_probe_created
          event_type :domain
        end
      RUBY

      definitions = EventEngine::DefinitionLoader.load!(dir)

      assert_equal [:loader_probe_created], definitions.map { |klass| klass.schema.event_name }
    end
  end

  test "load! includes the events generated by a lifecycle definition" do
    Dir.mktmpdir do |dir|
      File.write(File.join(dir, "loader_probe_lifecycle.rb"), <<~RUBY)
        class LoaderProbeLifecycle < EventEngine::LifecycleDefinition
          subject :loader_probe
          event_type :product
          lifecycle :started, :finished
        end
      RUBY

      definitions = EventEngine::DefinitionLoader.load!(dir)

      assert_equal [:loader_probe_started, :loader_probe_finished],
                   definitions.map { |klass| klass.schema.event_name }
    end
  end
end
